import { fp } from "@tscircuit/footprinter"
import type { AnyCircuitElement } from "circuit-json"

export type PreviewPadShape = "circle" | "pill" | "rect"
export type PreviewPadKind = "plated-hole" | "smt"

export interface PreviewPad {
  cornerRadius?: number
  height: number
  id: string
  kind: PreviewPadKind
  layer: string
  portHints: string[]
  rotation: number
  shape: PreviewPadShape
  width: number
  x: number
  y: number
}

export interface FootprintPreview {
  pads: PreviewPad[]
  sourceHints?: string[]
  subtitle: string
  title: string
}

export interface CircuitJsonPreviewOptions {
  sourceHints?: string[]
  subtitle?: string
  title?: string
}

type CircuitElement = AnyCircuitElement & Record<string, unknown>

const toNumber = (value: unknown, fallback = 0) => {
  if (typeof value === "number" && Number.isFinite(value)) return value
  if (typeof value === "string") {
    const parsed = Number.parseFloat(value)
    if (Number.isFinite(parsed)) return parsed
  }
  return fallback
}

const normalizePortHint = (hint: string) => {
  const trimmed = hint.trim()
  const pinMatch = trimmed.match(/^pin(\d+)$/i)
  if (pinMatch) return `pin${pinMatch[1]}`
  const numericMatch = trimmed.match(/^(\d+)$/)
  return numericMatch ? `pin${numericMatch[1]}` : trimmed
}

const normalizeShape = (
  shape: unknown,
  width: number,
  height: number,
): PreviewPadShape => {
  const normalized = typeof shape === "string" ? shape.toLowerCase() : "rect"
  if (normalized === "circle" || normalized === "ellipse") return "circle"
  if (normalized === "pill" || normalized === "oval") return "pill"
  if (Math.abs(width - height) < 0.00001 && normalized === "round") {
    return "circle"
  }
  return "rect"
}

const getCornerRadius = (
  element: CircuitElement,
  width: number,
  height: number,
) => {
  const radius = toNumber(
    element.corner_radius ?? element.cornerRadius ?? element.rect_border_radius,
  )
  return radius > 0 ? Math.min(radius, width / 2, height / 2) : undefined
}

export const circuitJsonToPreview = (
  circuitJson: readonly AnyCircuitElement[],
  options: CircuitJsonPreviewOptions = {},
): FootprintPreview => {
  const pads = circuitJson.flatMap((rawElement, index): PreviewPad[] => {
    const element = rawElement as CircuitElement
    if (element.type === "pcb_smtpad") {
      const width = toNumber(element.width)
      const height = toNumber(element.height)
      return [
        {
          cornerRadius: getCornerRadius(element, width, height),
          height,
          id: String(element.pcb_smtpad_id ?? `pcb_smtpad_${index + 1}`),
          kind: "smt",
          layer: String(element.layer ?? "top"),
          portHints: Array.isArray(element.port_hints)
            ? element.port_hints.map((hint) => normalizePortHint(String(hint)))
            : [],
          rotation: toNumber(element.rotation),
          shape: normalizeShape(element.shape, width, height),
          width,
          x: toNumber(element.x),
          y: toNumber(element.y),
        },
      ]
    }
    if (element.type === "pcb_plated_hole") {
      const width = toNumber(
        element.width ?? element.outer_diameter ?? element.outerDiameter,
        0.6,
      )
      const height = toNumber(element.height, width)
      return [
        {
          cornerRadius: getCornerRadius(element, width, height),
          height,
          id: String(
            element.pcb_plated_hole_id ?? `pcb_plated_hole_${index + 1}`,
          ),
          kind: "plated-hole",
          layer: Array.isArray(element.layers)
            ? String(element.layers[0] ?? "top")
            : "top",
          portHints: Array.isArray(element.port_hints)
            ? element.port_hints.map((hint) => normalizePortHint(String(hint)))
            : [],
          rotation: toNumber(element.rotation),
          shape: normalizeShape(element.shape ?? "circle", width, height),
          width,
          x: toNumber(element.x),
          y: toNumber(element.y),
        },
      ]
    }
    return []
  })

  if (pads.length === 0) {
    throw new Error(
      "Circuit JSON must contain at least one PCB SMT pad or plated hole",
    )
  }

  return {
    pads,
    sourceHints: options.sourceHints,
    subtitle: options.subtitle ?? "Circuit JSON footprint",
    title: options.title ?? "Circuit JSON",
  }
}

export const footprinterStringToPreview = (
  footprinterString: string,
): FootprintPreview => {
  const normalized = footprinterString.trim()
  if (!normalized) throw new Error("Footprinter string is required")
  return circuitJsonToPreview(
    fp.string(normalized).circuitJson() as AnyCircuitElement[],
    {
      subtitle: "Generated by @tscircuit/footprinter",
      title: normalized,
    },
  )
}
