import { fp } from "@tscircuit/footprinter"
import type {
  AnyCircuitElement,
  PcbHole,
  PcbPlatedHole,
  PcbSmtPad,
} from "circuit-json"
import { validatePcbPad } from "./preview-geometry.js"

export interface FootprintPreview {
  holes: PcbHole[]
  pads: Array<PcbSmtPad | PcbPlatedHole>
  sourceHints?: string[]
  subtitle: string
  title: string
}

export interface CircuitJsonPreviewOptions {
  sourceHints?: string[]
  subtitle?: string
  title?: string
}

const isPcbPad = (
  element: AnyCircuitElement,
): element is PcbSmtPad | PcbPlatedHole =>
  element.type === "pcb_smtpad" || element.type === "pcb_plated_hole"

const isPcbHole = (element: AnyCircuitElement): element is PcbHole =>
  element.type === "pcb_hole"

export const circuitJsonToPreview = (
  circuitJson: readonly AnyCircuitElement[],
  options: CircuitJsonPreviewOptions = {},
): FootprintPreview => {
  const pads = circuitJson.filter(isPcbPad)
  const holes = circuitJson.filter(isPcbHole)

  if (pads.length === 0) {
    throw new Error(
      "Circuit JSON must contain at least one PcbSmtPad or PcbPlatedHole",
    )
  }

  pads.forEach(validatePcbPad)

  return {
    holes,
    pads,
    sourceHints: options.sourceHints,
    subtitle: options.subtitle ?? "Circuit JSON footprint",
    title: options.title ?? "Circuit JSON",
  }
}

export const footprinterStringToPreview = (
  footprinterString: string,
): FootprintPreview => {
  const normalized = footprinterString.trim()
  if (!normalized) throw new Error("Footprinter string is required")
  return circuitJsonToPreview(
    fp.string(normalized).circuitJson() as AnyCircuitElement[],
    {
      subtitle: "Generated by @tscircuit/footprinter",
      title: normalized,
    },
  )
}
