import { fp } from "@tscircuit/footprinter"
import type {
  AnyCircuitElement,
  PcbHole,
  PcbPlatedHole,
  PcbSmtPad,
} from "circuit-json"
import { validatePcbPad } from "./footprint-geometry.js"

export interface Footprint {
  holes: PcbHole[]
  pads: Array<PcbSmtPad | PcbPlatedHole>
  rotation?: number
  sourceHints?: string[]
  subtitle: string
  title: string
  x?: number
  y?: number
}

export interface CircuitJsonToFootprintOptions {
  sourceHints?: string[]
  subtitle?: string
  title?: string
}

const isPcbPad = (
  element: AnyCircuitElement,
): element is PcbSmtPad | PcbPlatedHole =>
  element.type === "pcb_smtpad" || element.type === "pcb_plated_hole"

const isPcbHole = (element: AnyCircuitElement): element is PcbHole =>
  element.type === "pcb_hole"

const getPinNumberFromHints = (hints: readonly string[] | undefined) => {
  for (const hint of hints ?? []) {
    const match = hint.trim().match(/^(?:pin)?(\d+)$/i)
    if (match?.[1]) return Number.parseInt(match[1], 10)
  }
  return undefined
}

export const circuitJsonToFootprint = (
  circuitJson: readonly AnyCircuitElement[],
  options: CircuitJsonToFootprintOptions = {},
): Footprint => {
  const sourcePorts = circuitJson.filter(
    (element) => element.type === "source_port",
  )
  const pads = circuitJson.filter(isPcbPad).map((pad) => {
    const pinNumber = getPinNumberFromHints(pad.port_hints)
    if (pinNumber === undefined) return pad

    const sourcePort = sourcePorts.find(
      (port) =>
        port.pin_number === pinNumber ||
        getPinNumberFromHints([port.name]) === pinNumber,
    )
    if (!sourcePort) return pad

    return {
      ...pad,
      port_hints: [
        ...new Set([
          ...(pad.port_hints ?? []),
          sourcePort.name,
          ...(sourcePort.port_hints ?? []),
        ]),
      ],
    }
  })
  const holes = circuitJson.filter(isPcbHole)

  if (pads.length === 0) {
    throw new Error(
      "Circuit JSON must contain at least one PcbSmtPad or PcbPlatedHole",
    )
  }

  pads.forEach(validatePcbPad)

  return {
    holes,
    pads,
    rotation: 0,
    sourceHints: options.sourceHints,
    subtitle: options.subtitle ?? "Circuit JSON footprint",
    title: options.title ?? "Circuit JSON",
    x: 0,
    y: 0,
  }
}

export const footprinterStringToFootprint = (
  footprinterString: string,
): Footprint => {
  const normalized = footprinterString.trim()
  if (!normalized) throw new Error("Footprinter string is required")
  return circuitJsonToFootprint(fp.string(normalized).circuitJson(), {
    subtitle: "Generated by @tscircuit/footprinter",
    title: normalized,
  })
}
