import { type FootprinterParamsBuilder, fp } from "@tscircuit/footprinter"
import type {
  AnyCircuitElement,
  PcbHole,
  PcbPlatedHole,
  PcbSmtPad,
  PcbVia,
} from "circuit-json"
import { validatePcbPad } from "./footprint-geometry.js"

export interface Footprint {
  holes: PcbHole[]
  pads: Array<PcbSmtPad | PcbPlatedHole>
  rotation?: number
  sourceHints?: string[]
  subtitle: string
  title: string
  vias: PcbVia[]
  x?: number
  y?: number
}

export interface CircuitJsonToFootprintOptions {
  sourceHints?: string[]
  subtitle?: string
  title?: string
}

const isPcbPad = (
  element: AnyCircuitElement,
): element is PcbSmtPad | PcbPlatedHole =>
  element.type === "pcb_smtpad" || element.type === "pcb_plated_hole"

const isPcbHole = (element: AnyCircuitElement): element is PcbHole =>
  element.type === "pcb_hole"

const isPcbVia = (element: AnyCircuitElement): element is PcbVia =>
  element.type === "pcb_via"

const SOURCE_COMPONENT_FAMILY_HINTS: Record<string, string> = {
  simple_capacitor: "capacitor",
  simple_diode: "diode",
  simple_fuse: "fuse",
  simple_inductor: "inductor",
  simple_led: "led",
  simple_resistor: "resistor",
}

const getSourceComponentFamilyHints = (
  circuitJson: readonly AnyCircuitElement[],
  pads: Array<PcbSmtPad | PcbPlatedHole>,
) => {
  const pcbComponentIds = new Set(
    pads.flatMap((pad) => (pad.pcb_component_id ? [pad.pcb_component_id] : [])),
  )
  if (pcbComponentIds.size === 0) return []

  const sourceComponentIds = new Set(
    circuitJson.flatMap((element) =>
      element.type === "pcb_component" &&
      pcbComponentIds.has(element.pcb_component_id)
        ? [element.source_component_id]
        : [],
    ),
  )

  return [
    ...new Set(
      circuitJson.flatMap((element) => {
        if (
          element.type !== "source_component" ||
          !sourceComponentIds.has(element.source_component_id) ||
          !element.ftype
        ) {
          return []
        }
        const hint = SOURCE_COMPONENT_FAMILY_HINTS[element.ftype]
        return hint ? [hint] : []
      }),
    ),
  ]
}

export const circuitJsonToFootprint = (
  circuitJson: readonly AnyCircuitElement[],
  options: CircuitJsonToFootprintOptions = {},
): Footprint => {
  const pads = circuitJson.filter(isPcbPad)
  const holes = circuitJson.filter(isPcbHole)
  const vias = circuitJson.filter(isPcbVia)

  if (pads.length === 0) {
    throw new Error(
      "Circuit JSON must contain at least one PcbSmtPad or PcbPlatedHole",
    )
  }

  pads.forEach(validatePcbPad)

  const sourceComponentFamilyHints = getSourceComponentFamilyHints(
    circuitJson,
    pads,
  )

  return {
    holes,
    pads,
    rotation: 0,
    sourceHints: [
      ...(options.sourceHints ?? []),
      ...sourceComponentFamilyHints,
    ],
    subtitle: options.subtitle ?? "Circuit JSON footprint",
    title: options.title ?? "Circuit JSON",
    vias,
    x: 0,
    y: 0,
  }
}

export const footprinterStringToFootprint = (
  footprinterString: string,
): Footprint => {
  const normalized = footprinterString.trim()
  if (!normalized) throw new Error("Footprinter string is required")
  const builder = fp.string(normalized)
  const usesRectangularBgaPads =
    /^bga(?:\d|_)/i.test(normalized) && /_rectpads(?:_|$)/i.test(normalized)
  // string() is typed without family modifiers, but returns the same proxy as bga().
  const bgaBuilder =
    builder as unknown as FootprinterParamsBuilder<"circularpads">
  const circuitJson = usesRectangularBgaPads
    ? bgaBuilder.circularpads(false).circuitJson()
    : builder.circuitJson()

  return circuitJsonToFootprint(circuitJson, {
    subtitle: "Generated by @tscircuit/footprinter",
    title: normalized,
  })
}
