import { fp } from "@tscircuit/footprinter"
import type {
  AnyCircuitElement,
  PcbHole,
  PcbPlatedHole,
  PcbSmtPad,
  PcbVia,
} from "circuit-json"
import { validatePcbPad } from "./footprint-geometry.js"

export interface Footprint {
  holes: PcbHole[]
  pads: Array<PcbSmtPad | PcbPlatedHole>
  rotation?: number
  sourceHints?: string[]
  subtitle: string
  title: string
  vias: PcbVia[]
  x?: number
  y?: number
}

export interface CircuitJsonToFootprintOptions {
  sourceHints?: string[]
  subtitle?: string
  title?: string
}

const isPcbPad = (
  element: AnyCircuitElement,
): element is PcbSmtPad | PcbPlatedHole =>
  element.type === "pcb_smtpad" || element.type === "pcb_plated_hole"

const isPcbHole = (element: AnyCircuitElement): element is PcbHole =>
  element.type === "pcb_hole"

const isPcbVia = (element: AnyCircuitElement): element is PcbVia =>
  element.type === "pcb_via"

export const circuitJsonToFootprint = (
  circuitJson: readonly AnyCircuitElement[],
  options: CircuitJsonToFootprintOptions = {},
): Footprint => {
  const pads = circuitJson.filter(isPcbPad)
  const holes = circuitJson.filter(isPcbHole)
  const vias = circuitJson.filter(isPcbVia)

  if (pads.length === 0) {
    throw new Error(
      "Circuit JSON must contain at least one PcbSmtPad or PcbPlatedHole",
    )
  }

  pads.forEach(validatePcbPad)

  return {
    holes,
    pads,
    rotation: 0,
    sourceHints: options.sourceHints,
    subtitle: options.subtitle ?? "Circuit JSON footprint",
    title: options.title ?? "Circuit JSON",
    vias,
    x: 0,
    y: 0,
  }
}

export const footprinterStringToFootprint = (
  footprinterString: string,
): Footprint => {
  const normalized = footprinterString.trim()
  if (!normalized) throw new Error("Footprinter string is required")
  return circuitJsonToFootprint(fp.string(normalized).circuitJson(), {
    subtitle: "Generated by @tscircuit/footprinter",
    title: normalized,
  })
}
